name = "PebbleGame"
uuid = "7fda980f-9fd9-427b-8afe-9e93946f984e"
authors = ["Yusheng Zhao <yushengzhao2020@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LuxorGraphPlot = "1f49bdf2-22a7-4bc4-978b-948dc219fbbc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
